modLoader = "javafml"
loaderVersion = "[${loaderVersion},)"
license = "LGPL-3.0"

[[mods]]
modId = "moremcmeta_emissive_plugin"
version = "${modVersion}"
displayName = "MoreMcmeta Emissive Textures Plugin"
authors = "soir20"
description = '''
Plugin for MoreMcmeta to enable emissive textures for blocks, items, entities, and block entities.
'''

[[dependencies.moremcmeta_emissive_plugin]]
modId = "moremcmeta"
mandatory = true
versionRange = "[${minMoreMcmetaVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.moremcmeta_emissive_plugin]]
modId = "forge"
mandatory = true
versionRange = "[${loaderVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moremcmeta_emissive_plugin]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"